### PR TITLE
add option to manually select which package to install

### PR DESCRIPTION
**Pull request by stonewell**

### CODE REVIEW

**Comment by Rishang** [comment]
can you please provide example and description of what it will do

**Comment by eloo** [comment]
@Rishang not sure if this really applies to this PR

but i guess the idea of this change is to have an option to skip the autodetection for the binary to download.
this is useful when the autodetection is not working correctly.. 
i have seen this with jump for arm processors

image

```
Linux odroidn2 5.19.17-meson64 #22.11.1 SMP PREEMPT Wed Nov 30 11:05:42 UTC 2022 aarch64 GNU/Linux
```

it suggests an amd64 binary for aarch64
the correct binary would be `jump_linux_arm_binary`

https://github.com/gsamokovarov/jump/releases

so maybe the autodetection could be improved here but having the option to manually select would be a good workaround for weird scenarios anyway

**Comment by Rishang** [comment]
if it is'nt working for arm, then it needs to i will try it on any arm device

**Comment by Rishang** [comment]
It finds words based on (this)[https://github.com/Rishang/install-release/blob/main/InstallRelease/constants.py] file you can try changing code and testng over this file and test it in debug mode using `install-release get -v` flag

**Pull request closed without merging**
